import fs from "node:fs/promises"; let data={generated_at:null,count:0,products:[]}; try{data=JSON.parse(await fs.readFile("data/products/latest.json","utf8"))}catch{}
const ps=data.products||[], fa=n=>new Intl.NumberFormat("fa-IR").format(n), money=n=>n==null?"—":fa(n)+" تومان";
const cats=[...new Set(ps.map(p=>p.category_label).filter(Boolean))];
const discounted=ps.filter(p=>p.discount_percent>0).sort((a,b)=>b.discount_percent-a.discount_percent);
const moved=ps.filter(p=>p.signals?.price_change_pct!=null).sort((a,b)=>a.signals.price_change_pct-b.signals.price_change_pct);
const topRated=ps.filter(p=>p.rating_count>=20).sort((a,b)=>(b.rating||0)-(a.rating||0));
const card=(p,note)=>`<article><div class="tag">${p.category_label||""}</div><a href="${p.url||"#"}" target="_blank"><b>${p.title||"بدون عنوان"}</b></a><div class="price">${money(p.price)}</div><small>${note||p.seller||""}</small></article>`;
const cards=(arr,note)=>arr.slice(0,4).map(p=>card(p,typeof note==="function"?note(p):note)).join("")||'<p class="empty">با جمع شدن تاریخچه، سیگنال‌های این بخش ظاهر می‌شوند.</p>';
const rows=ps.slice(0,50).map(p=>`<tr><td><a href="${p.url||"#"}" target="_blank">${p.title||"بدون عنوان"}</a><small>${p.seller||""}</small></td><td>${p.category_label||"—"}</td><td>${money(p.price)}</td><td>${p.discount_percent?p.discount_percent+"٪":"—"}</td><td>${p.rating??"—"}</td><td>${p.signals?.price_change_pct==null?"—":(p.signals.price_change_pct>0?"+":"")+p.signals.price_change_pct+"٪"}</td></tr>`).join("");
const html=`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Radar Iran — نبض بازار مصرف ایران</title><style>*{box-sizing:border-box}body{font-family:system-ui,-apple-system,sans-serif;max-width:1320px;margin:auto;padding:28px;background:#090b0e;color:#f4f4f5}header{padding:5vh 0 2vh}h1{font-size:clamp(3rem,9vw,7rem);margin:0;letter-spacing:-.05em}h1 b{color:#ff3b30}h2{margin:44px 0 8px}p,small{color:#9ca3af}.lead{font-size:1.15rem;max-width:760px;line-height:2}.stats,.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin:22px 0}.stat,article{border:1px solid #292d35;background:#12151a;border-radius:16px;padding:18px}.stat strong{font-size:1.7rem;display:block}.tag{font-size:.75rem;color:#ff6259;margin-bottom:10px}article b{line-height:1.7}.price{font-size:1.15rem;font-weight:700;margin:15px 0 4px}a{color:#fff;text-decoration:none}.how{border:1px solid #292d35;border-radius:18px;padding:22px;margin-top:28px;background:#0e1116}.how b{color:#fff}.how p{margin:6px 0;line-height:1.9}table{width:100%;border-collapse:collapse;background:#12151a;border:1px solid #292d35;border-radius:18px;overflow:hidden;margin-bottom:60px}th,td{text-align:right;padding:14px;border-bottom:1px solid #292d35}th{color:#9ca3af;font-size:.8rem}td small{display:block;margin-top:5px}.empty{padding:18px}@media(max-width:760px){body{padding:18px}th:nth-child(2),td:nth-child(2),th:nth-child(5),td:nth-child(5){display:none}table{font-size:.8rem}}</style></head><body><header><small>نبض بازار مصرف ایران · بروزرسانی ساعتی</small><h1>RADAR <b>IRAN</b></h1><p class="lead">رادار ایران به‌جای یک فهرست محصول، تغییرات بازار را دنبال می‌کند: چه چیزی واقعاً ارزان‌تر شده، کدام تخفیف ارزش بررسی دارد و جایگاه محصولات چگونه تغییر می‌کند.</p></header>
<section class="stats"><div class="stat"><small>محصولات زیر نظر</small><strong>${fa(data.count||0)}</strong></div><div class="stat"><small>دسته‌های فعال</small><strong>${fa(cats.length)}</strong></div><div class="stat"><small>دارای تخفیف فعلی</small><strong>${fa(discounted.length)}</strong></div><div class="stat"><small>آخرین رصد</small><strong style="font-size:1rem">${data.generated_at?new Date(data.generated_at).toLocaleString("fa-IR"):"—"}</strong></div></section>
<div class="how"><b>این صفحه به چه درد می‌خورد؟</b><p>اگر قصد خرید داری، «افت قیمت» و «تخفیف‌های قابل بررسی» را ببین. اگر بازار را دنبال می‌کنی، تغییر جایگاه محصولات را رصد کن. با بیشتر شدن تاریخچه، رادار تخفیف واقعی را از تخفیف اسمی و جهش‌های غیرعادی را از نوسان معمول جدا می‌کند.</p></div>
<h2>تخفیف‌های قابل بررسی</h2><p>بالاترین درصد تخفیف فعلی؛ فعلاً تخفیف اعلام‌شده فروشگاه است و پس از شکل‌گیری تاریخچه با قیمت گذشته راستی‌آزمایی می‌شود.</p><section class="grid">${cards(discounted,p=>p.discount_percent+"٪ تخفیف · "+(p.seller||""))}</section>
<h2>افت قیمت نسبت به رصد قبلی</h2><p>این بخش بعد از حداقل دو مشاهدهٔ قابل مقایسه معنی پیدا می‌کند.</p><section class="grid">${cards(moved.filter(p=>p.signals.price_change_pct<0),p=>p.signals.price_change_pct+"٪ نسبت به مشاهده قبل")}</section>
<h2>محصولات با امتیاز بالا</h2><p>برای جلوگیری از امتیازهای کم‌نمونه، فقط محصولاتی با حداقل ۲۰ رأی.</p><section class="grid">${cards(topRated,p=>"امتیاز "+p.rating+" از "+fa(p.rating_count)+" رأی")}</section>
<h2>دادهٔ کامل رصد</h2><table><thead><tr><th>محصول</th><th>دسته</th><th>قیمت</th><th>تخفیف</th><th>امتیاز</th><th>تغییر قیمت</th></tr></thead><tbody>${rows||'<tr><td colspan="6">هنوز داده‌ای ثبت نشده است.</td></tr>'}</tbody></table></body></html>`;
await fs.mkdir("dist",{recursive:true});await fs.writeFile("dist/index.html",html);